CREATE TABLE IF NOT EXISTS public.lead_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa INTEGER NOT NULL,
  nome VARCHAR(120) NOT NULL,
  cor VARCHAR(20) NOT NULL DEFAULT 'verde',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_lead_tags_empresa_nome ON public.lead_tags (id_empresa, lower(nome));
CREATE INDEX IF NOT EXISTS idx_lead_tags_empresa ON public.lead_tags (id_empresa);

CREATE TABLE IF NOT EXISTS public.lead_tag_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id INTEGER NOT NULL REFERENCES public."BASE_DE_LEADS"(id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES public.lead_tags(id) ON DELETE CASCADE,
  id_empresa INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT lead_tag_assignments_unique UNIQUE (lead_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_lead_tag_assignments_empresa ON public.lead_tag_assignments (id_empresa, lead_id);

DO $$
BEGIN
  IF to_regclass('public.etiquetas') IS NOT NULL THEN
    INSERT INTO public.lead_tags (id_empresa, nome, cor, created_at, updated_at)
    SELECT id_empresa, nome,
      CASE upper(cor)
        WHEN '#38BDF8' THEN 'azul_claro' WHEN '#3B82F6' THEN 'azul_escuro'
        WHEN '#22C55E' THEN 'verde' WHEN '#EF4444' THEN 'vermelho'
        WHEN '#F59E0B' THEN 'amarelo' WHEN '#A855F7' THEN 'roxo'
        WHEN '#EC4899' THEN 'vermelho' ELSE 'verde'
      END,
      created_at, COALESCE(updated_at, NOW())
    FROM public.etiquetas
    ON CONFLICT DO NOTHING;
  END IF;
END $$;

ALTER TABLE public.lead_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_tag_assignments ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lead_tags, public.lead_tag_assignments TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

CREATE POLICY "lead_tags_client_access" ON public.lead_tags FOR ALL TO anon, authenticated USING (id_empresa > 0) WITH CHECK (id_empresa > 0);
CREATE POLICY "lead_tag_assignments_client_access" ON public.lead_tag_assignments FOR ALL TO anon, authenticated USING (id_empresa > 0) WITH CHECK (id_empresa > 0);
